import test from 'node:test';
import assert from 'node:assert/strict';
import {database,migrate} from '../server/sqlite.mjs';
import {ensureUser,saveProfile,runMatching,feed,setLike,dismiss,shanghaiDay,accountState} from '../server/service.mjs';
import {api} from '../server/api.mjs';
const T=Date.parse('2026-09-18T04:00:00Z')/1000;
const birth={nickname:'测试',birthDate:'1999-05-18',birthTime:'09:30',city:'上海',bio:'测试资料',interests:['咖啡'],gender:'unspecified',seeking:'any',minAge:18,maxAge:100,consent:true};
async function setup(n=50){const db=database();migrate(db);for(let i=0;i<n;i++){const id='u'+String(i).padStart(3,'0');await ensureUser(db,id,T);await saveProfile(db,id,{...birth,nickname:'用户'+i},T)}return db}
const pair=(db,a,b,now=T,versions=[1,1])=>db.prepare('INSERT INTO recommendation_pairs(id,day,a,b,a_version,b_version,score,reasons,created_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),shanghaiDay(now),...[a,b].sort(),...versions,80,'[]',now).run();
test('reciprocal recommendation is atomic and rejects 21st for either recipient',async()=>{const db=await setup();for(let i=1;i<=19;i++)await pair(db,'u000','u'+String(i).padStart(3,'0'));const results=await Promise.allSettled([pair(db,'u000','u020'),pair(db,'u000','u021')]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await accountState(db,'u000',T)).recommendationUsed,20);assert.equal((await feed(db,'u020',T)).length+(await feed(db,'u021',T)).length,1);await assert.rejects(pair(db,'u000','u022'),/DAILY_RECOMMENDATION_LIMIT/);assert.equal((await feed(db,'u022',T)).length,0);db.close()});
test('skip never refunds cumulative daily quota, history is immutable',async()=>{const db=await setup();for(let i=1;i<=20;i++)await pair(db,'u000','u'+String(i).padStart(3,'0'));for(const item of await feed(db,'u000',T))await dismiss(db,'u000',item.pairId);assert.equal((await feed(db,'u000',T)).length,0);assert.equal((await accountState(db,'u000',T)).recommendationUsed,20);await assert.rejects(pair(db,'u000','u021'),/DAILY_RECOMMENDATION_LIMIT/);await assert.rejects(db.prepare('DELETE FROM recommendation_pairs').run(),/IMMUTABLE/);await assert.rejects(db.prepare("UPDATE recommendation_pairs SET day='2026-09-19'").run(),/IMMUTABLE/);db.close()});
test('Shanghai midnight resets recommendations but not likes',async()=>{assert.equal(shanghaiDay(Date.parse('2026-09-18T15:59:59Z')/1000),'2026-09-18');assert.equal(shanghaiDay(Date.parse('2026-09-18T16:00:00Z')/1000),'2026-09-19');const db=await setup();for(let i=1;i<=20;i++){const id='u'+String(i).padStart(3,'0');await pair(db,'u000',id);await setLike(db,'u000',id,true,T)}const tomorrow=T+86400;assert.equal((await accountState(db,'u000',tomorrow)).recommendationUsed,0);assert.equal((await accountState(db,'u000',tomorrow)).likeUsed,20);await pair(db,'u000','u021',tomorrow);await assert.rejects(setLike(db,'u000','u021',true,tomorrow),/LIKE_LIMIT/);db.close()});
test('like cap holds for concurrent requests, duplicates, unlike and reactivation',async()=>{const db=await setup();for(let i=1;i<=22;i++)await pair(db,'u000','u'+String(i).padStart(3,'0'),i<=20?T:T+86400);for(let i=1;i<=19;i++)await setLike(db,'u000','u'+String(i).padStart(3,'0'),true,T);const results=await Promise.allSettled([setLike(db,'u000','u020',true,T),setLike(db,'u000','u021',true,T)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);await setLike(db,'u000','u001',true,T);assert.equal((await accountState(db,'u000',T)).likeUsed,20);await setLike(db,'u000','u001',false,T);await setLike(db,'u000','u021',true,T);await assert.rejects(setLike(db,'u000','u001',true,T),/LIKE_LIMIT/);assert.equal((await accountState(db,'u000',T)).likeUsed,20);await assert.rejects(db.prepare('INSERT INTO likes(sender,recipient,active,created_at) VALUES(?,?,2,?)').bind('u000','u040',T).run(),/INVALID_LIKE/);await db.prepare('INSERT INTO likes(sender,recipient,active,created_at) VALUES(?,?,0,?)').bind('u003','u040',T).run();await assert.rejects(db.prepare('UPDATE likes SET active=1 WHERE sender=? AND recipient=?').bind('u003','u040').run(),/NOT_RECOMMENDED/);db.close()});
test('consent, stale versions, adulthood, pair identity and privacy are enforced',async()=>{const db=await setup(6);await db.prepare('UPDATE users SET consent=0 WHERE id=?').bind('u001').run();await assert.rejects(pair(db,'u000','u001'),/PROFILE_CHANGED/);await db.prepare("UPDATE users SET birth_date='2020-01-01' WHERE id='u002'").run();await assert.rejects(pair(db,'u000','u002'),/PROFILE_CHANGED/);await db.prepare('UPDATE users SET version=2 WHERE id=?').bind('u003').run();await assert.rejects(pair(db,'u000','u003'),/PROFILE_CHANGED/);await pair(db,'u000','u004');const out=(await feed(db,'u000',T))[0];assert.equal(out.id,'u004');for(const forbidden of ['birth_date','birth_time','chart','password_hash','username'])assert.equal(Object.hasOwn(out,forbidden),false);await assert.rejects(setLike(db,'u000','u005',true,T),/NOT_RECOMMENDED/);await setLike(db,'u000','u004',true,T);await saveProfile(db,'u004',{...birth,consent:false},T);assert.equal((await accountState(db,'u000',T)).likeUsed,0);assert.equal((await accountState(db,'u000',T)).recommendationUsed,1);assert.equal((await feed(db,'u000',T)).length,0);db.close()});
test('global allocation respects mutual preferences, quota, duplicates and cooldown',async()=>{const db=await setup(45);await saveProfile(db,'u044',{...birth,consent:false},T);const result=await runMatching(db,{now:T,clock:()=>T});assert.ok(result.created>0);for(let i=0;i<44;i++){const id='u'+String(i).padStart(3,'0');const s=await accountState(db,id,T);assert.ok(s.recommendationUsed<=20);const list=await feed(db,id,T);for(const p of list)assert.ok((await feed(db,p.id,T)).some(x=>x.id===id))}assert.equal((await feed(db,'u044',T)).length,0);assert.equal((await runMatching(db,{now:T+1,clock:()=>T+1})).busy,true);const count=db.raw.prepare('SELECT count(*) n FROM recommendation_pairs').get().n;await runMatching(db,{now:T+30,clock:()=>T+30});assert.equal(db.raw.prepare('SELECT count(*) n FROM recommendation_pairs').get().n,count);db.close()});
test('matcher stops when its trusted clock crosses Shanghai midnight',async()=>{const db=await setup(3);const before=Date.parse('2026-09-18T15:59:59Z')/1000;const result=await runMatching(db,{now:before,clock:()=>before+2});assert.equal(result.created,0);db.close()});
test('API rejects missing identity, cross-origin mutation, and forged ownership',async()=>{const db=await setup(4);await pair(db,'u000','u001');const unauth=await api(new Request('https://example.test/api/me'),db,null,{now:T});assert.equal(unauth.status,401);const evil=await api(new Request('https://example.test/api/likes',{method:'POST',headers:{Origin:'https://evil.test','Content-Type':'application/json'},body:JSON.stringify({targetId:'u001'})}),db,'u000',{now:T});assert.equal(evil.status,403);const forged=await api(new Request('https://example.test/api/likes',{method:'POST',headers:{Origin:'https://example.test','Content-Type':'application/json'},body:JSON.stringify({sender:'u000',targetId:'u001'})}),db,'u002',{now:T});assert.equal(forged.status,409);assert.equal((await accountState(db,'u000',T)).likeUsed,0);db.close()});
